import type { LucideIcon } from 'lucide-react';
import {
  BadgeDollarSign,
  Building2,
  BookOpen,
  Briefcase,
  Calendar,
  ChartBar,
  Check,
  ClipboardList,
  Clock,
  Coffee,
  Code,
  Cog,
  Dumbbell,
  Eye,
  FileText,
  Flag,
  Flower2,
  Footprints,
  Gift,
  GraduationCap,
  Hammer,
  Handshake,
  Key,
  Laptop,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  Megaphone,
  Moon,
  Music,
  Paintbrush,
  Pause,
  PenLine,
  Phone,
  PiggyBank,
  Presentation,
  Rocket,
  Search,
  Sparkles,
  Sprout,
  Stethoscope,
  Star,
  Target,
  TestTube,
  TreePalm,
  Truck,
  Utensils,
  UtensilsCrossed,
  Wrench,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  office: Building2,
  computer: Laptop,
  documents: FileText,
  presentation: Presentation,
  meeting: Handshake,
  phone: Phone,
  email: Mail,
  calendar: Calendar,
  clock: Clock,
  writing: PenLine,
  design: Paintbrush,
  development: Code,
  research: Search,
  analytics: ChartBar,
  planning: ClipboardList,
  review: Eye,
  testing: TestTube,
  maintenance: Wrench,
  support: LifeBuoy,
  gardening: Sprout,
  cooking: UtensilsCrossed,
  cleaning: Sparkles,
  delivery: Truck,
  construction: Hammer,
  education: GraduationCap,
  healthcare: Stethoscope,
  finance: PiggyBank,
  sales: BadgeDollarSign,
  marketing: Megaphone,
  coffee: Coffee,
  lunch: Utensils,
  break: Pause,
  walk: Footprints,
  exercise: Dumbbell,
  meditation: Flower2,
  reading: BookOpen,
  music: Music,
  rest: Moon,
  vacation: TreePalm,
  star: Star,
  check: Check,
  flag: Flag,
  target: Target,
  rocket: Rocket,
  bulb: Lightbulb,
  gear: Cog,
  key: Key,
  lock: Lock,
  gift: Gift,
};

export function getIcon(id?: string | null): LucideIcon {
  return (id && ICONS[id]) || ICONS.briefcase;
}

