import type { LucideIcon } from 'lucide-react';
import {
  Anvil,
  BadgeDollarSign,
  Boxes,
  BrickWall,
  Building2,
  BookOpen,
  Briefcase,
  Calendar,
  CakeSlice,
  Candy,
  ChartBar,
  Check,
  ClipboardList,
  Clock,
  Coffee,
  Code,
  Cog,
  CookingPot,
  Croissant,
  CupSoda,
  Dumbbell,
  Eye,
  FileText,
  Flag,
  Flower2,
  Footprints,
  Gem,
  Handshake,
  Gift,
  GraduationCap,
  Hammer,
  HardHat,
  HeartPulse,
  Key,
  LandPlot,
  Laptop,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Moon,
  Music,
  Paintbrush,
  Palette,
  PencilRuler,
  Pause,
  PenLine,
  Phone,
  PiggyBank,
  Presentation,
  Rocket,
  Scale,
  Scissors,
  Search,
  Shirt,
  ShowerHead,
  Sparkles,
  Sprout,
  Stethoscope,
  Star,
  ShoppingCart,
  Target,
  TestTube,
  Tractor,
  TreePalm,
  Trees,
  Truck,
  Utensils,
  UtensilsCrossed,
  Warehouse,
  Wrench,
  Zap,
} from 'lucide-react';
import { PotteryIcon } from './custom';

export const ICONS: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  office: Building2,
  computer: Laptop,
  documents: FileText,
  presentation: Presentation,
  meeting: Handshake,
  phone: Phone,
  email: Mail,
  calendar: Calendar,
  clock: Clock,
  writing: PenLine,
  design: Paintbrush,
  development: Code,
  research: Search,
  analytics: ChartBar,
  planning: ClipboardList,
  review: Eye,
  testing: TestTube,
  maintenance: Wrench,
  manual_work: HardHat,
  construction: LandPlot,
  repair: Hammer,
  brickwork: BrickWall,
  carpentry: PencilRuler,
  painting: Paintbrush,
  plumbing: ShowerHead,
  electrician: Zap,
  gardening: Sprout,
  landscaping: Trees,
  farming: Tractor,
  cleaning: Sparkles,
  delivery: Truck,
  warehouse: Warehouse,
  support: LifeBuoy,
  consulting: MessageSquare,
  education: GraduationCap,
  healthcare: Stethoscope,
  finance: PiggyBank,
  sales: BadgeDollarSign,
  marketing: Megaphone,
  legal: Scale,
  logistics: Boxes,
  coffee: Coffee,
  tea: CupSoda,
  breakfast: Croissant,
  lunch: Utensils,
  dinner: CookingPot,
  snack: Candy,
  bakery: CakeSlice,
  cooking: UtensilsCrossed,
  shopping: ShoppingCart,
  break: Pause,
  walk: Footprints,
  exercise: Dumbbell,
  meditation: Flower2,
  reading: BookOpen,
  music: Music,
  rest: Moon,
  vacation: TreePalm,
  health: HeartPulse,
  star: Star,
  check: Check,
  flag: Flag,
  target: Target,
  rocket: Rocket,
  bulb: Lightbulb,
  gear: Cog,
  key: Key,
  lock: Lock,
  gift: Gift,
  jewelry: Gem,
  crafting: Palette,
  sewing: Scissors,
  tailoring: Shirt,
  metalwork: Anvil,
  pottery: PotteryIcon,
};

export function getIcon(id?: string | null): LucideIcon {
  return (id && ICONS[id]) || ICONS.briefcase;
}

